services:
  postgres:
    image: postgres:17.6-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "7421:5432"

  sqlx:
    build: .
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations